# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.expression_pca import ExpressionPCA

class TestExpressionPCA(unittest.TestCase):
    """ExpressionPCA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExpressionPCA:
        """Test ExpressionPCA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExpressionPCA`
        """
        model = ExpressionPCA()
        if include_optional:
            return ExpressionPCA(
                pc1 = 1.337,
                pc2 = 1.337,
                pc3 = 1.337,
                sample_id = '',
                tissue_site_detail_id = 'Adipose_Subcutaneous',
                ontology_id = 'UBERON:EFO_0000572',
                dataset_id = 'gtex_v8'
            )
        else:
            return ExpressionPCA(
                pc1 = 1.337,
                pc2 = 1.337,
                pc3 = 1.337,
                sample_id = '',
                tissue_site_detail_id = 'Adipose_Subcutaneous',
                ontology_id = 'UBERON:EFO_0000572',
                dataset_id = 'gtex_v8',
        )
        """

    def testExpressionPCA(self):
        """Test ExpressionPCA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
