# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_single_nucleus_gene_expression_summary import PaginatedResponseSingleNucleusGeneExpressionSummary

class TestPaginatedResponseSingleNucleusGeneExpressionSummary(unittest.TestCase):
    """PaginatedResponseSingleNucleusGeneExpressionSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseSingleNucleusGeneExpressionSummary:
        """Test PaginatedResponseSingleNucleusGeneExpressionSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseSingleNucleusGeneExpressionSummary`
        """
        model = PaginatedResponseSingleNucleusGeneExpressionSummary()
        if include_optional:
            return PaginatedResponseSingleNucleusGeneExpressionSummary(
                data = [
                    gtex_openapi.models.single_nucleus_gene_expression_summary.SingleNucleusGeneExpressionSummary(
                        tissue_site_detail_id = 'Adipose_Subcutaneous', 
                        ontology_id = 'UBERON:EFO_0000572', 
                        dataset_id = 'gtex_v8', 
                        cell_type = '', 
                        num_cells = 56, )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseSingleNucleusGeneExpressionSummary(
                data = [
                    gtex_openapi.models.single_nucleus_gene_expression_summary.SingleNucleusGeneExpressionSummary(
                        tissue_site_detail_id = 'Adipose_Subcutaneous', 
                        ontology_id = 'UBERON:EFO_0000572', 
                        dataset_id = 'gtex_v8', 
                        cell_type = '', 
                        num_cells = 56, )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseSingleNucleusGeneExpressionSummary(self):
        """Test PaginatedResponseSingleNucleusGeneExpressionSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
