# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.gwas import GWAS

class TestGWAS(unittest.TestCase):
    """GWAS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GWAS:
        """Test GWAS
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GWAS`
        """
        model = GWAS()
        if include_optional:
            return GWAS(
                chromosome = 'chr1',
                start = 56,
                end = 56,
                phenotype = '',
                p_value = 1.337,
                beta = 1.337,
                pubmed_id = 56,
                snp_id = '',
                risk_allele = '',
                genome_build = 'GRCh38/hg38'
            )
        else:
            return GWAS(
                chromosome = 'chr1',
                start = 56,
                end = 56,
                phenotype = '',
                pubmed_id = 56,
                snp_id = '',
                genome_build = 'GRCh38/hg38',
        )
        """

    def testGWAS(self):
        """Test GWAS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
