# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.expression_data_endpoints_api import ExpressionDataEndpointsApi


class TestExpressionDataEndpointsApi(unittest.TestCase):
    """ExpressionDataEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpressionDataEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_clustered_median_exon_expression_api_v2_expression_clustered_median_exon_expression_get(self) -> None:
        """Test case for get_clustered_median_exon_expression_api_v2_expression_clustered_median_exon_expression_get

        Get Clustered Median Exon Expression
        """
        pass

    def test_get_clustered_median_gene_expression_api_v2_expression_clustered_median_gene_expression_get(self) -> None:
        """Test case for get_clustered_median_gene_expression_api_v2_expression_clustered_median_gene_expression_get

        Get Clustered Median Gene Expression
        """
        pass

    def test_get_clustered_median_junction_expression_api_v2_expression_clustered_median_junction_expression_get(self) -> None:
        """Test case for get_clustered_median_junction_expression_api_v2_expression_clustered_median_junction_expression_get

        Get Clustered Median Junction Expression
        """
        pass

    def test_get_clustered_median_transcript_expression_api_v2_expression_clustered_median_transcript_expression_get(self) -> None:
        """Test case for get_clustered_median_transcript_expression_api_v2_expression_clustered_median_transcript_expression_get

        Get Clustered Median Transcript Expression
        """
        pass

    def test_get_expression_pca_api_v2_expression_expression_pca_get(self) -> None:
        """Test case for get_expression_pca_api_v2_expression_expression_pca_get

        Get Expression Pca
        """
        pass

    def test_get_gene_expression_api_v2_expression_gene_expression_get(self) -> None:
        """Test case for get_gene_expression_api_v2_expression_gene_expression_get

        Get Gene Expression
        """
        pass

    def test_get_median_exon_expression_api_v2_expression_median_exon_expression_get(self) -> None:
        """Test case for get_median_exon_expression_api_v2_expression_median_exon_expression_get

        Get Median Exon Expression
        """
        pass

    def test_get_median_gene_expression_api_v2_expression_median_gene_expression_get(self) -> None:
        """Test case for get_median_gene_expression_api_v2_expression_median_gene_expression_get

        Get Median Gene Expression
        """
        pass

    def test_get_median_junction_expression_api_v2_expression_median_junction_expression_get(self) -> None:
        """Test case for get_median_junction_expression_api_v2_expression_median_junction_expression_get

        Get Median Junction Expression
        """
        pass

    def test_get_median_transcript_expression_api_v2_expression_median_transcript_expression_get(self) -> None:
        """Test case for get_median_transcript_expression_api_v2_expression_median_transcript_expression_get

        Get Median Transcript Expression
        """
        pass

    def test_get_single_nucleus_gex_api_v2_expression_single_nucleus_gene_expression_get(self) -> None:
        """Test case for get_single_nucleus_gex_api_v2_expression_single_nucleus_gene_expression_get

        Get Single Nucleus Gex
        """
        pass

    def test_get_single_nucleus_gex_summary_api_v2_expression_single_nucleus_gene_expression_summary_get(self) -> None:
        """Test case for get_single_nucleus_gex_summary_api_v2_expression_single_nucleus_gene_expression_summary_get

        Get Single Nucleus Gex Summary
        """
        pass

    def test_get_top_expressed_genes_api_v2_expression_top_expressed_gene_get(self) -> None:
        """Test case for get_top_expressed_genes_api_v2_expression_top_expressed_gene_get

        Get Top Expressed Genes
        """
        pass


if __name__ == '__main__':
    unittest.main()
