# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.dynamic_association_endpoints_api import DynamicAssociationEndpointsApi


class TestDynamicAssociationEndpointsApi(unittest.TestCase):
    """DynamicAssociationEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DynamicAssociationEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_calculate_expression_quantitative_trait_loci_api_v2_association_dyneqtl_post(self) -> None:
        """Test case for bulk_calculate_expression_quantitative_trait_loci_api_v2_association_dyneqtl_post

        Bulk Calculate Expression Quantitative Trait Loci
        """
        pass

    def test_calculate_expression_quantitative_trait_loci_api_v2_association_dyneqtl_get(self) -> None:
        """Test case for calculate_expression_quantitative_trait_loci_api_v2_association_dyneqtl_get

        Calculate Expression Quantitative Trait Loci
        """
        pass

    def test_calculate_ieqtls_api_v2_association_dynieqtl_get(self) -> None:
        """Test case for calculate_ieqtls_api_v2_association_dynieqtl_get

        Calculate Ieqtls
        """
        pass

    def test_calculate_isqtls_api_v2_association_dynisqtl_get(self) -> None:
        """Test case for calculate_isqtls_api_v2_association_dynisqtl_get

        Calculate Isqtls
        """
        pass

    def test_calculate_splicing_quantitative_trait_loci_api_v2_association_dynsqtl_get(self) -> None:
        """Test case for calculate_splicing_quantitative_trait_loci_api_v2_association_dynsqtl_get

        Calculate Splicing Quantitative Trait Loci
        """
        pass


if __name__ == '__main__':
    unittest.main()
