# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.gtex_portal_api_info_api import GTExPortalAPIInfoApi


class TestGTExPortalAPIInfoApi(unittest.TestCase):
    """GTExPortalAPIInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GTExPortalAPIInfoApi()

    def tearDown(self) -> None:
        pass

    def test_get_service_info_api_v2_get(self) -> None:
        """Test case for get_service_info_api_v2_get

        Get Service Info
        """
        pass


if __name__ == '__main__':
    unittest.main()
