# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.tissue_level_metasoft_info import TissueLevelMetasoftInfo

class TestTissueLevelMetasoftInfo(unittest.TestCase):
    """TissueLevelMetasoftInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TissueLevelMetasoftInfo:
        """Test TissueLevelMetasoftInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TissueLevelMetasoftInfo`
        """
        model = TissueLevelMetasoftInfo()
        if include_optional:
            return TissueLevelMetasoftInfo(
                m_value = 1.337,
                p_value = 1.337,
                se = 1.337,
                nes = 1.337
            )
        else:
            return TissueLevelMetasoftInfo(
        )
        """

    def testTissueLevelMetasoftInfo(self):
        """Test TissueLevelMetasoftInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
