# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.static_association_endpoints_api import StaticAssociationEndpointsApi


class TestStaticAssociationEndpointsApi(unittest.TestCase):
    """StaticAssociationEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StaticAssociationEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_eqtl_genes_api_v2_association_egene_get(self) -> None:
        """Test case for get_eqtl_genes_api_v2_association_egene_get

        Get Eqtl Genes
        """
        pass

    def test_get_fine_mapping_api_v2_association_fine_mapping_get(self) -> None:
        """Test case for get_fine_mapping_api_v2_association_fine_mapping_get

        Get Fine Mapping
        """
        pass

    def test_get_independent_eqtl_api_v2_association_independent_eqtl_get(self) -> None:
        """Test case for get_independent_eqtl_api_v2_association_independent_eqtl_get

        Get Independent Eqtl
        """
        pass

    def test_get_multi_tissue_eqtls_api_v2_association_metasoft_get(self) -> None:
        """Test case for get_multi_tissue_eqtls_api_v2_association_metasoft_get

        Get Multi Tissue Eqtls
        """
        pass

    def test_get_significant_single_tissue_eqtls_api_v2_association_single_tissue_eqtl_get(self) -> None:
        """Test case for get_significant_single_tissue_eqtls_api_v2_association_single_tissue_eqtl_get

        Get Significant Single Tissue Eqtls
        """
        pass

    def test_get_significant_single_tissue_eqtls_by_location_api_v2_association_single_tissue_eqtl_by_location_get(self) -> None:
        """Test case for get_significant_single_tissue_eqtls_by_location_api_v2_association_single_tissue_eqtl_by_location_get

        Get Significant Single Tissue Eqtls By Location
        """
        pass

    def test_get_significant_single_tissue_ieqtls_api_v2_association_single_tissue_i_eqtl_get(self) -> None:
        """Test case for get_significant_single_tissue_ieqtls_api_v2_association_single_tissue_i_eqtl_get

        Get Significant Single Tissue Ieqtls
        """
        pass

    def test_get_significant_single_tissue_isqtls_api_v2_association_single_tissue_i_sqtl_get(self) -> None:
        """Test case for get_significant_single_tissue_isqtls_api_v2_association_single_tissue_i_sqtl_get

        Get Significant Single Tissue Isqtls
        """
        pass

    def test_get_significant_single_tissue_sqtls_api_v2_association_single_tissue_sqtl_get(self) -> None:
        """Test case for get_significant_single_tissue_sqtls_api_v2_association_single_tissue_sqtl_get

        Get Significant Single Tissue Sqtls
        """
        pass

    def test_get_sqtl_genes_api_v2_association_sgene_get(self) -> None:
        """Test case for get_sqtl_genes_api_v2_association_sgene_get

        Get Sqtl Genes
        """
        pass


if __name__ == '__main__':
    unittest.main()
