# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_histology_sample import PaginatedResponseHistologySample

class TestPaginatedResponseHistologySample(unittest.TestCase):
    """PaginatedResponseHistologySample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseHistologySample:
        """Test PaginatedResponseHistologySample
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseHistologySample`
        """
        model = PaginatedResponseHistologySample()
        if include_optional:
            return PaginatedResponseHistologySample(
                data = [
                    gtex_openapi.models.histology_sample.HistologySample(
                        age_bracket = '20-29', 
                        hardy_scale = 'Ventilator case', 
                        hide = True, 
                        histology_image_id = '', 
                        pathology_notes = '', 
                        pathology_notes_categories = {
                            'key' : True
                            }, 
                        sample_id = '', 
                        sex = 'male', 
                        subject_id = '', 
                        tissue_sample_id = '', 
                        tissue_site_detail = '', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseHistologySample(
                data = [
                    gtex_openapi.models.histology_sample.HistologySample(
                        age_bracket = '20-29', 
                        hardy_scale = 'Ventilator case', 
                        hide = True, 
                        histology_image_id = '', 
                        pathology_notes = '', 
                        pathology_notes_categories = {
                            'key' : True
                            }, 
                        sample_id = '', 
                        sex = 'male', 
                        subject_id = '', 
                        tissue_sample_id = '', 
                        tissue_site_detail = '', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseHistologySample(self):
        """Test PaginatedResponseHistologySample"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
