# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_single_tissue_eqtl import PaginatedResponseSingleTissueEqtl

class TestPaginatedResponseSingleTissueEqtl(unittest.TestCase):
    """PaginatedResponseSingleTissueEqtl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseSingleTissueEqtl:
        """Test PaginatedResponseSingleTissueEqtl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseSingleTissueEqtl`
        """
        model = PaginatedResponseSingleTissueEqtl()
        if include_optional:
            return PaginatedResponseSingleTissueEqtl(
                data = [
                    gtex_openapi.models.single_tissue_eqtl.SingleTissueEqtl(
                        snp_id = '', 
                        pos = 56, 
                        snp_id_upper = '', 
                        variant_id = '', 
                        gene_symbol = '', 
                        p_value = 1.337, 
                        gene_symbol_upper = '', 
                        dataset_id = 'gtex_v8', 
                        tissue_site_detail_id = 'Adipose_Subcutaneous', 
                        ontology_id = 'UBERON:EFO_0000572', 
                        chromosome = 'chr1', 
                        gencode_id = '', 
                        nes = 1.337, )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseSingleTissueEqtl(
                data = [
                    gtex_openapi.models.single_tissue_eqtl.SingleTissueEqtl(
                        snp_id = '', 
                        pos = 56, 
                        snp_id_upper = '', 
                        variant_id = '', 
                        gene_symbol = '', 
                        p_value = 1.337, 
                        gene_symbol_upper = '', 
                        dataset_id = 'gtex_v8', 
                        tissue_site_detail_id = 'Adipose_Subcutaneous', 
                        ontology_id = 'UBERON:EFO_0000572', 
                        chromosome = 'chr1', 
                        gencode_id = '', 
                        nes = 1.337, )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseSingleTissueEqtl(self):
        """Test PaginatedResponseSingleTissueEqtl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
