# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.histology_sample import HistologySample

class TestHistologySample(unittest.TestCase):
    """HistologySample unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistologySample:
        """Test HistologySample
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistologySample`
        """
        model = HistologySample()
        if include_optional:
            return HistologySample(
                age_bracket = '20-29',
                hardy_scale = 'Ventilator case',
                hide = True,
                histology_image_id = '',
                pathology_notes = '',
                pathology_notes_categories = {
                    'key' : True
                    },
                sample_id = '',
                sex = 'male',
                subject_id = '',
                tissue_sample_id = '',
                tissue_site_detail = ''
            )
        else:
            return HistologySample(
                age_bracket = '20-29',
                hardy_scale = 'Ventilator case',
                hide = True,
                histology_image_id = '',
                pathology_notes_categories = {
                    'key' : True
                    },
                sex = 'male',
                subject_id = '',
                tissue_site_detail = '',
        )
        """

    def testHistologySample(self):
        """Test HistologySample"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
