# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.app_models_responses_material_type import AppModelsResponsesMaterialType

class TestAppModelsResponsesMaterialType(unittest.TestCase):
    """AppModelsResponsesMaterialType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppModelsResponsesMaterialType(self):
        """Test AppModelsResponsesMaterialType"""
        # inst = AppModelsResponsesMaterialType()

if __name__ == '__main__':
    unittest.main()
