# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.service_info import ServiceInfo

class TestServiceInfo(unittest.TestCase):
    """ServiceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceInfo:
        """Test ServiceInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceInfo`
        """
        model = ServiceInfo()
        if include_optional:
            return ServiceInfo(
                id = '',
                name = '',
                version = '',
                organization = gtex_openapi.models.organization.Organization(
                    name = '', 
                    url = '', ),
                description = '',
                contact_url = '',
                documentation_url = '',
                created_at = '',
                updated_at = '',
                environment = ''
            )
        else:
            return ServiceInfo(
                id = '',
                name = '',
                version = '',
                organization = gtex_openapi.models.organization.Organization(
                    name = '', 
                    url = '', ),
        )
        """

    def testServiceInfo(self):
        """Test ServiceInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
