# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.ischemic_time_group import IschemicTimeGroup

class TestIschemicTimeGroup(unittest.TestCase):
    """IschemicTimeGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIschemicTimeGroup(self):
        """Test IschemicTimeGroup"""
        # inst = IschemicTimeGroup()

if __name__ == '__main__':
    unittest.main()
