# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.post_eqtl_error import PostEqtlError

class TestPostEqtlError(unittest.TestCase):
    """PostEqtlError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostEqtlError:
        """Test PostEqtlError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostEqtlError`
        """
        model = PostEqtlError()
        if include_optional:
            return PostEqtlError(
                error_message = '',
                variant_id = '',
                gencode_id = '',
                tissue_site_detail_id = 'Adipose_Subcutaneous'
            )
        else:
            return PostEqtlError(
                error_message = '',
        )
        """

    def testPostEqtlError(self):
        """Test PostEqtlError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
