# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_news_item import PaginatedResponseNewsItem

class TestPaginatedResponseNewsItem(unittest.TestCase):
    """PaginatedResponseNewsItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseNewsItem:
        """Test PaginatedResponseNewsItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseNewsItem`
        """
        model = PaginatedResponseNewsItem()
        if include_optional:
            return PaginatedResponseNewsItem(
                data = [
                    gtex_openapi.models.news_item.NewsItem(
                        title = '', 
                        news_text = '', 
                        rank = 56, 
                        date_created = null, 
                        release = '', 
                        id = 56, )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseNewsItem(
                data = [
                    gtex_openapi.models.news_item.NewsItem(
                        title = '', 
                        news_text = '', 
                        rank = 56, 
                        date_created = null, 
                        release = '', 
                        id = 56, )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseNewsItem(self):
        """Test PaginatedResponseNewsItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
