# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.tissue_site_detail_id import TissueSiteDetailId

class TestTissueSiteDetailId(unittest.TestCase):
    """TissueSiteDetailId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTissueSiteDetailId(self):
        """Test TissueSiteDetailId"""
        # inst = TissueSiteDetailId()

if __name__ == '__main__':
    unittest.main()
