# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.variant import Variant

class TestVariant(unittest.TestCase):
    """Variant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Variant:
        """Test Variant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Variant`
        """
        model = Variant()
        if include_optional:
            return Variant(
                snp_id = '',
                b37_variant_id = '',
                pos = 56,
                maf01 = True,
                variant_id = '',
                alt = '',
                chromosome = 'chr1',
                snp_id_upper = '',
                dataset_id = '',
                ref = '',
                shorthand = ''
            )
        else:
            return Variant(
                snp_id = '',
                b37_variant_id = '',
                pos = 56,
                maf01 = True,
                variant_id = '',
                alt = '',
                chromosome = 'chr1',
                snp_id_upper = '',
                dataset_id = '',
                ref = '',
        )
        """

    def testVariant(self):
        """Test Variant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
