# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_gwas import PaginatedResponseGWAS

class TestPaginatedResponseGWAS(unittest.TestCase):
    """PaginatedResponseGWAS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseGWAS:
        """Test PaginatedResponseGWAS
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseGWAS`
        """
        model = PaginatedResponseGWAS()
        if include_optional:
            return PaginatedResponseGWAS(
                data = [
                    gtex_openapi.models.gwas.GWAS(
                        chromosome = 'chr1', 
                        start = 56, 
                        end = 56, 
                        phenotype = '', 
                        p_value = 1.337, 
                        beta = 1.337, 
                        pubmed_id = 56, 
                        snp_id = '', 
                        risk_allele = '', 
                        genome_build = 'GRCh38/hg38', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseGWAS(
                data = [
                    gtex_openapi.models.gwas.GWAS(
                        chromosome = 'chr1', 
                        start = 56, 
                        end = 56, 
                        phenotype = '', 
                        p_value = 1.337, 
                        beta = 1.337, 
                        pubmed_id = 56, 
                        snp_id = '', 
                        risk_allele = '', 
                        genome_build = 'GRCh38/hg38', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseGWAS(self):
        """Test PaginatedResponseGWAS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
