# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.sqtl import Sqtl

class TestSqtl(unittest.TestCase):
    """Sqtl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Sqtl:
        """Test Sqtl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Sqtl`
        """
        model = Sqtl()
        if include_optional:
            return Sqtl(
                data = [
                    1.337
                    ],
                error = 1.337,
                genotypes = [
                    56
                    ],
                het_count = 56,
                homo_alt_count = 56,
                homo_ref_count = 56,
                maf = 1.337,
                nes = 1.337,
                p_value = 1.337,
                p_value_threshold = 1.337,
                phenotype_id = '',
                t_statistic = 1.337,
                tissue_site_detail_id = 'Adipose_Subcutaneous',
                variant_id = ''
            )
        else:
            return Sqtl(
                data = [
                    1.337
                    ],
                error = 1.337,
                genotypes = [
                    56
                    ],
                het_count = 56,
                homo_alt_count = 56,
                homo_ref_count = 56,
                maf = 1.337,
                nes = 1.337,
                p_value = 1.337,
                p_value_threshold = 1.337,
                phenotype_id = '',
                t_statistic = 1.337,
                tissue_site_detail_id = 'Adipose_Subcutaneous',
                variant_id = '',
        )
        """

    def testSqtl(self):
        """Test Sqtl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
