# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.igv_response import IGVResponse

class TestIGVResponse(unittest.TestCase):
    """IGVResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IGVResponse:
        """Test IGVResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IGVResponse`
        """
        model = IGVResponse()
        if include_optional:
            return IGVResponse(
                dataset_id = '',
                single_tissue_eqtl = [
                    gtex_openapi.models.single_tissue_eqtl.singleTissueEqtl(
                        chromosome = 'chr1', 
                        dataset_id = '', 
                        gencode_id = '', 
                        gene_symbol = '', 
                        gene_symbol_upper = '', 
                        nes = 1.337, 
                        p_value = 1.337, 
                        pos = 56, 
                        snp_id = '', 
                        tissue_site_detail_id = '', 
                        variant_id = '', )
                    ]
            )
        else:
            return IGVResponse(
                dataset_id = '',
                single_tissue_eqtl = [
                    gtex_openapi.models.single_tissue_eqtl.singleTissueEqtl(
                        chromosome = 'chr1', 
                        dataset_id = '', 
                        gencode_id = '', 
                        gene_symbol = '', 
                        gene_symbol_upper = '', 
                        nes = 1.337, 
                        p_value = 1.337, 
                        pos = 56, 
                        snp_id = '', 
                        tissue_site_detail_id = '', 
                        variant_id = '', )
                    ],
        )
        """

    def testIGVResponse(self):
        """Test IGVResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
