# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_single_tissue_i_eqtl import PaginatedResponseSingleTissueIEqtl

class TestPaginatedResponseSingleTissueIEqtl(unittest.TestCase):
    """PaginatedResponseSingleTissueIEqtl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseSingleTissueIEqtl:
        """Test PaginatedResponseSingleTissueIEqtl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseSingleTissueIEqtl`
        """
        model = PaginatedResponseSingleTissueIEqtl()
        if include_optional:
            return PaginatedResponseSingleTissueIEqtl(
                data = [
                    gtex_openapi.models.single_tissue_i_eqtl.SingleTissueIEqtl(
                        snp_id = '', 
                        b_gise = 1.337, 
                        pos = 56, 
                        snp_id_upper = '', 
                        p_value_g = 1.337, 
                        p_value_gi = 1.337, 
                        gene_symbol = '', 
                        gene_symbol_upper = '', 
                        p_value_i = 1.337, 
                        b_gi = 1.337, 
                        tissue_site_detail_id = 'Adipose_Subcutaneous', 
                        ontology_id = 'UBERON:EFO_0000572', 
                        chromosome = 'chr1', 
                        tissue_cell_type = 'Adipocytes', 
                        tss_distance = 56, 
                        b_gse = 1.337, 
                        variant_id = '', 
                        maf = 1.337, 
                        b_ise = 1.337, 
                        dataset_id = 'gtex_v8', 
                        b_g = 1.337, 
                        p_value_adjusted_bh = 1.337, 
                        b_i = 1.337, 
                        gencode_id = '', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseSingleTissueIEqtl(
                data = [
                    gtex_openapi.models.single_tissue_i_eqtl.SingleTissueIEqtl(
                        snp_id = '', 
                        b_gise = 1.337, 
                        pos = 56, 
                        snp_id_upper = '', 
                        p_value_g = 1.337, 
                        p_value_gi = 1.337, 
                        gene_symbol = '', 
                        gene_symbol_upper = '', 
                        p_value_i = 1.337, 
                        b_gi = 1.337, 
                        tissue_site_detail_id = 'Adipose_Subcutaneous', 
                        ontology_id = 'UBERON:EFO_0000572', 
                        chromosome = 'chr1', 
                        tissue_cell_type = 'Adipocytes', 
                        tss_distance = 56, 
                        b_gse = 1.337, 
                        variant_id = '', 
                        maf = 1.337, 
                        b_ise = 1.337, 
                        dataset_id = 'gtex_v8', 
                        b_g = 1.337, 
                        p_value_adjusted_bh = 1.337, 
                        b_i = 1.337, 
                        gencode_id = '', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseSingleTissueIEqtl(self):
        """Test PaginatedResponseSingleTissueIEqtl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
