# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.admin_endpoints_api import AdminEndpointsApi


class TestAdminEndpointsApi(unittest.TestCase):
    """AdminEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_maintenance_message_api_v2_admin_maintenance_message_get(self) -> None:
        """Test case for get_maintenance_message_api_v2_admin_maintenance_message_get

        Get Maintenance Message
        """
        pass

    def test_get_news_item_api_v2_admin_news_item_get(self) -> None:
        """Test case for get_news_item_api_v2_admin_news_item_get

        Get News Item
        """
        pass


if __name__ == '__main__':
    unittest.main()
