# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.metadata_endpoints_api import MetadataEndpointsApi


class TestMetadataEndpointsApi(unittest.TestCase):
    """MetadataEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetadataEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_dataset_info_api_v2_metadata_dataset_get(self) -> None:
        """Test case for get_dataset_info_api_v2_metadata_dataset_get

        Get Dataset Info
        """
        pass


if __name__ == '__main__':
    unittest.main()
