# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.paginated_response_collapsed_gene_model_exon import PaginatedResponseCollapsedGeneModelExon

class TestPaginatedResponseCollapsedGeneModelExon(unittest.TestCase):
    """PaginatedResponseCollapsedGeneModelExon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseCollapsedGeneModelExon:
        """Test PaginatedResponseCollapsedGeneModelExon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseCollapsedGeneModelExon`
        """
        model = PaginatedResponseCollapsedGeneModelExon()
        if include_optional:
            return PaginatedResponseCollapsedGeneModelExon(
                data = [
                    gtex_openapi.models.collapsed_gene_model_exon.CollapsedGeneModelExon(
                        feature_type = '', 
                        end = 56, 
                        genome_build = 'GRCh38/hg38', 
                        chromosome = 'chr1', 
                        exon_number = '', 
                        gene_symbol_upper = '', 
                        exon_id = '', 
                        dataset_id = '', 
                        start = 56, 
                        data_source = '', 
                        gencode_id = '', 
                        gene_symbol = '', 
                        gencode_version = 'v39', 
                        strand = '+', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, )
            )
        else:
            return PaginatedResponseCollapsedGeneModelExon(
                data = [
                    gtex_openapi.models.collapsed_gene_model_exon.CollapsedGeneModelExon(
                        feature_type = '', 
                        end = 56, 
                        genome_build = 'GRCh38/hg38', 
                        chromosome = 'chr1', 
                        exon_number = '', 
                        gene_symbol_upper = '', 
                        exon_id = '', 
                        dataset_id = '', 
                        start = 56, 
                        data_source = '', 
                        gencode_id = '', 
                        gene_symbol = '', 
                        gencode_version = 'v39', 
                        strand = '+', )
                    ],
                paging_info = gtex_openapi.models.pagination_info.PaginationInfo(
                    number_of_pages = 56, 
                    page = 56, 
                    max_items_per_page = 56, 
                    total_number_of_items = 56, ),
        )
        """

    def testPaginatedResponseCollapsedGeneModelExon(self):
        """Test PaginatedResponseCollapsedGeneModelExon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
