# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.histology_endpoints_api import HistologyEndpointsApi


class TestHistologyEndpointsApi(unittest.TestCase):
    """HistologyEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistologyEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_image_api_v2_histology_image_get(self) -> None:
        """Test case for get_image_api_v2_histology_image_get

        Get Image
        """
        pass


if __name__ == '__main__':
    unittest.main()
