# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.open_access_folder import OpenAccessFolder

class TestOpenAccessFolder(unittest.TestCase):
    """OpenAccessFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenAccessFolder:
        """Test OpenAccessFolder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenAccessFolder`
        """
        model = OpenAccessFolder()
        if include_optional:
            return OpenAccessFolder(
                name = '',
                display_name = '',
                description = '',
                order = 56,
                parent = '',
                children = gtex_openapi.models.open_access_folder_children.OpenAccessFolderChildren(
                    files = [
                        gtex_openapi.models.open_access_file.OpenAccessFile(
                            display_name = '', 
                            description = '', 
                            file_size = 56, 
                            url = '', 
                            order = 56, 
                            parent = '', )
                        ], 
                    folders = [
                        gtex_openapi.models.open_access_folder.OpenAccessFolder(
                            name = '', 
                            display_name = '', 
                            description = '', 
                            order = 56, 
                            parent = '', 
                            children = gtex_openapi.models.open_access_folder_children.OpenAccessFolderChildren(
                                files = [
                                    gtex_openapi.models.open_access_file.OpenAccessFile(
                                        display_name = '', 
                                        description = '', 
                                        file_size = 56, 
                                        url = '', 
                                        order = 56, 
                                        parent = '', )
                                    ], 
                                folders = [
                                    gtex_openapi.models.open_access_folder.OpenAccessFolder(
                                        name = '', 
                                        display_name = '', 
                                        description = '', 
                                        order = 56, 
                                        parent = '', 
                                        children = , )
                                    ], ), )
                        ], )
            )
        else:
            return OpenAccessFolder(
                name = '',
                display_name = '',
                description = '',
                order = 56,
                parent = '',
                children = gtex_openapi.models.open_access_folder_children.OpenAccessFolderChildren(
                    files = [
                        gtex_openapi.models.open_access_file.OpenAccessFile(
                            display_name = '', 
                            description = '', 
                            file_size = 56, 
                            url = '', 
                            order = 56, 
                            parent = '', )
                        ], 
                    folders = [
                        gtex_openapi.models.open_access_folder.OpenAccessFolder(
                            name = '', 
                            display_name = '', 
                            description = '', 
                            order = 56, 
                            parent = '', 
                            children = gtex_openapi.models.open_access_folder_children.OpenAccessFolderChildren(
                                files = [
                                    gtex_openapi.models.open_access_file.OpenAccessFile(
                                        display_name = '', 
                                        description = '', 
                                        file_size = 56, 
                                        url = '', 
                                        order = 56, 
                                        parent = '', )
                                    ], 
                                folders = [
                                    gtex_openapi.models.open_access_folder.OpenAccessFolder(
                                        name = '', 
                                        display_name = '', 
                                        description = '', 
                                        order = 56, 
                                        parent = '', 
                                        children = , )
                                    ], ), )
                        ], ),
        )
        """

    def testOpenAccessFolder(self):
        """Test OpenAccessFolder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
