# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.biobank_data_endpoints_api import BiobankDataEndpointsApi


class TestBiobankDataEndpointsApi(unittest.TestCase):
    """BiobankDataEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BiobankDataEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_download_api_v2_biobank_download_get(self) -> None:
        """Test case for download_api_v2_biobank_download_get

        Download
        """
        pass

    def test_get_sample_api_v2_biobank_sample_get(self) -> None:
        """Test case for get_sample_api_v2_biobank_sample_get

        Get Sample
        """
        pass


if __name__ == '__main__':
    unittest.main()
