# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.app_models_responses_gencode_version import AppModelsResponsesGencodeVersion

class TestAppModelsResponsesGencodeVersion(unittest.TestCase):
    """AppModelsResponsesGencodeVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppModelsResponsesGencodeVersion(self):
        """Test AppModelsResponsesGencodeVersion"""
        # inst = AppModelsResponsesGencodeVersion()

if __name__ == '__main__':
    unittest.main()
