# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.post_eqtl import PostEqtl

class TestPostEqtl(unittest.TestCase):
    """PostEqtl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostEqtl:
        """Test PostEqtl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostEqtl`
        """
        model = PostEqtl()
        if include_optional:
            return PostEqtl(
                dataset_id = 'gtex_v8',
                error = None,
                gencode_id = '',
                gene_symbol = '',
                message = '',
                nes = None,
                p_value = None,
                p_value_threshold = None,
                snp_id = '',
                t_statistic = None,
                tissue_site_detail_id = 'Adipose_Subcutaneous',
                variant_id = ''
            )
        else:
            return PostEqtl(
                dataset_id = 'gtex_v8',
                error = None,
                gencode_id = '',
                nes = None,
                p_value = None,
                p_value_threshold = None,
                t_statistic = None,
                tissue_site_detail_id = 'Adipose_Subcutaneous',
                variant_id = '',
        )
        """

    def testPostEqtl(self):
        """Test PostEqtl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
