# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.models.collapsed_gene_model_exon import CollapsedGeneModelExon

class TestCollapsedGeneModelExon(unittest.TestCase):
    """CollapsedGeneModelExon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollapsedGeneModelExon:
        """Test CollapsedGeneModelExon
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollapsedGeneModelExon`
        """
        model = CollapsedGeneModelExon()
        if include_optional:
            return CollapsedGeneModelExon(
                feature_type = '',
                end = 56,
                genome_build = 'GRCh38/hg38',
                chromosome = 'chr1',
                exon_number = '',
                gene_symbol_upper = '',
                exon_id = '',
                dataset_id = '',
                start = 56,
                data_source = '',
                gencode_id = '',
                gene_symbol = '',
                gencode_version = 'v39',
                strand = '+'
            )
        else:
            return CollapsedGeneModelExon(
                feature_type = '',
                end = 56,
                genome_build = 'GRCh38/hg38',
                chromosome = 'chr1',
                exon_number = '',
                gene_symbol_upper = '',
                exon_id = '',
                dataset_id = '',
                start = 56,
                data_source = '',
                gencode_id = '',
                gene_symbol = '',
                gencode_version = 'v39',
                strand = '+',
        )
        """

    def testCollapsedGeneModelExon(self):
        """Test CollapsedGeneModelExon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
