# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gtex_openapi.api.reference_genome_endpoints_api import ReferenceGenomeEndpointsApi


class TestReferenceGenomeEndpointsApi(unittest.TestCase):
    """ReferenceGenomeEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferenceGenomeEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_get_exons_api_v2_reference_exon_get(self) -> None:
        """Test case for get_exons_api_v2_reference_exon_get

        Get Exons
        """
        pass

    def test_get_gene_search_api_v2_reference_gene_search_get(self) -> None:
        """Test case for get_gene_search_api_v2_reference_gene_search_get

        Get Gene Search
        """
        pass

    def test_get_genes_api_v2_reference_gene_get(self) -> None:
        """Test case for get_genes_api_v2_reference_gene_get

        Get Genes
        """
        pass

    def test_get_genomic_features_api_v2_reference_features_feature_id_get(self) -> None:
        """Test case for get_genomic_features_api_v2_reference_features_feature_id_get

        Get Genomic Features
        """
        pass

    def test_get_gwas_catalog_by_location_api_v2_reference_gwas_catalog_by_location_get(self) -> None:
        """Test case for get_gwas_catalog_by_location_api_v2_reference_gwas_catalog_by_location_get

        Get Gwas Catalog By Location
        """
        pass

    def test_get_neighbor_gene_api_v2_reference_neighbor_gene_get(self) -> None:
        """Test case for get_neighbor_gene_api_v2_reference_neighbor_gene_get

        Get Neighbor Gene
        """
        pass

    def test_get_transcripts_api_v2_reference_transcript_get(self) -> None:
        """Test case for get_transcripts_api_v2_reference_transcript_get

        Get Transcripts
        """
        pass


if __name__ == '__main__':
    unittest.main()
