# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AgeAndCountSummary(BaseModel):
    """
    Holds summary statistics for a collection of samples.
    """ # noqa: E501
    age_max: Optional[StrictInt] = Field(default=None, alias="ageMax")
    age_min: Optional[StrictInt] = Field(default=None, alias="ageMin")
    age_mean: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="ageMean")
    count: StrictInt
    __properties: ClassVar[List[str]] = ["ageMax", "ageMin", "ageMean", "count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgeAndCountSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if age_max (nullable) is None
        # and model_fields_set contains the field
        if self.age_max is None and "age_max" in self.model_fields_set:
            _dict['ageMax'] = None

        # set to None if age_min (nullable) is None
        # and model_fields_set contains the field
        if self.age_min is None and "age_min" in self.model_fields_set:
            _dict['ageMin'] = None

        # set to None if age_mean (nullable) is None
        # and model_fields_set contains the field
        if self.age_mean is None and "age_mean" in self.model_fields_set:
            _dict['ageMean'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgeAndCountSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ageMax": obj.get("ageMax"),
            "ageMin": obj.get("ageMin"),
            "ageMean": obj.get("ageMean"),
            "count": obj.get("count")
        })
        return _obj


