# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppModelsRequestParametersMaterialType(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    CELLS_COLON_CELL_LINE_VIABLE = 'Cells:Cell Line Viable'
    DNA_COLON_DNA_GENOMIC = 'DNA:DNA Genomic'
    DNA_COLON_DNA_SOMATIC = 'DNA:DNA Somatic'
    RNA_COLON_TOTAL_RNA = 'RNA:Total RNA'
    TISSUE_COLON_PA_XGENE_PRESERVED = 'Tissue:PAXgene Preserved'
    TISSUE_COLON_PA_XGENE_PRESERVED_PARAFFIN_MINUS_EMBEDDED = 'Tissue:PAXgene Preserved Paraffin-embedded'
    TISSUE_COLON_FRESH_FROZEN_TISSUE = 'Tissue:Fresh Frozen Tissue'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppModelsRequestParametersMaterialType from a JSON string"""
        return cls(json.loads(json_str))


