# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppModelsRequestParametersHardyScale(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    VENTILATOR_CASE = 'Ventilator case'
    FAST_DEATH_MINUS__VIOLENT = 'Fast death - violent'
    FAST_DEATH_MINUS__NATURAL_CAUSES = 'Fast death - natural causes'
    INTERMEDIATE_DEATH = 'Intermediate death'
    SLOW_DEATH = 'Slow death'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppModelsRequestParametersHardyScale from a JSON string"""
        return cls(json.loads(json_str))


