# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppModelsRequestParametersGenomeBuild(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    GRCH38_SLASH_HG38 = 'GRCh38/hg38'
    GRCH37_SLASH_HG19 = 'GRCh37/hg19'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppModelsRequestParametersGenomeBuild from a JSON string"""
        return cls(json.loads(json_str))


