# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from gtex_openapi.models.app_models_responses_hardy_scale import AppModelsResponsesHardyScale
from gtex_openapi.models.app_models_responses_material_type import AppModelsResponsesMaterialType
from gtex_openapi.models.donor_age_bracket import DonorAgeBracket
from gtex_openapi.models.original_material_type import OriginalMaterialType
from gtex_openapi.models.sex import Sex
from gtex_openapi.models.tissue_site_detail_id import TissueSiteDetailId
from typing import Optional, Set
from typing_extensions import Self

class BiobankSample(BaseModel):
    """
    BiobankSample
    """ # noqa: E501
    material_type: AppModelsResponsesMaterialType = Field(alias="materialType")
    sample_id: StrictStr = Field(alias="sampleId")
    sample_id_upper: StrictStr = Field(alias="sampleIdUpper")
    sex: Sex
    rin: Optional[Union[StrictFloat, StrictInt]] = None
    has_gtex_image: StrictBool = Field(alias="hasGTExImage")
    concentration: Optional[Union[StrictFloat, StrictInt]] = None
    autolysis_score: Optional[StrictStr] = Field(default=None, alias="autolysisScore")
    analysis_release: Optional[StrictStr] = Field(default=None, alias="analysisRelease")
    genotype: Optional[StrictStr] = None
    hardy_scale: Optional[AppModelsResponsesHardyScale] = Field(default=None, alias="hardyScale")
    pathology_notes: StrictStr = Field(alias="pathologyNotes")
    subject_id: StrictStr = Field(alias="subjectId")
    tissue_site_detail_id: TissueSiteDetailId = Field(alias="tissueSiteDetailId")
    has_genotype: StrictBool = Field(alias="hasGenotype")
    original_material_type: OriginalMaterialType = Field(alias="originalMaterialType")
    aliquot_id: StrictStr = Field(alias="aliquotId")
    tissue_sample_id: StrictStr = Field(alias="tissueSampleId")
    age_bracket: DonorAgeBracket = Field(alias="ageBracket")
    brain_tissue_donor: StrictBool = Field(alias="brainTissueDonor")
    volume: Optional[Union[StrictFloat, StrictInt]] = None
    has_expression_data: StrictBool = Field(alias="hasExpressionData")
    has_brd_image: StrictBool = Field(alias="hasBRDImage")
    tissue_site_detail: StrictStr = Field(alias="tissueSiteDetail")
    pathology_notes_categories: Dict[str, StrictBool] = Field(alias="pathologyNotesCategories")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    mass: Optional[Union[StrictFloat, StrictInt]] = None
    tissue_site: StrictStr = Field(alias="tissueSite")
    expression: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["materialType", "sampleId", "sampleIdUpper", "sex", "rin", "hasGTExImage", "concentration", "autolysisScore", "analysisRelease", "genotype", "hardyScale", "pathologyNotes", "subjectId", "tissueSiteDetailId", "hasGenotype", "originalMaterialType", "aliquotId", "tissueSampleId", "ageBracket", "brainTissueDonor", "volume", "hasExpressionData", "hasBRDImage", "tissueSiteDetail", "pathologyNotesCategories", "amount", "mass", "tissueSite", "expression"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BiobankSample from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rin (nullable) is None
        # and model_fields_set contains the field
        if self.rin is None and "rin" in self.model_fields_set:
            _dict['rin'] = None

        # set to None if concentration (nullable) is None
        # and model_fields_set contains the field
        if self.concentration is None and "concentration" in self.model_fields_set:
            _dict['concentration'] = None

        # set to None if autolysis_score (nullable) is None
        # and model_fields_set contains the field
        if self.autolysis_score is None and "autolysis_score" in self.model_fields_set:
            _dict['autolysisScore'] = None

        # set to None if analysis_release (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_release is None and "analysis_release" in self.model_fields_set:
            _dict['analysisRelease'] = None

        # set to None if genotype (nullable) is None
        # and model_fields_set contains the field
        if self.genotype is None and "genotype" in self.model_fields_set:
            _dict['genotype'] = None

        # set to None if hardy_scale (nullable) is None
        # and model_fields_set contains the field
        if self.hardy_scale is None and "hardy_scale" in self.model_fields_set:
            _dict['hardyScale'] = None

        # set to None if volume (nullable) is None
        # and model_fields_set contains the field
        if self.volume is None and "volume" in self.model_fields_set:
            _dict['volume'] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        # set to None if mass (nullable) is None
        # and model_fields_set contains the field
        if self.mass is None and "mass" in self.model_fields_set:
            _dict['mass'] = None

        # set to None if expression (nullable) is None
        # and model_fields_set contains the field
        if self.expression is None and "expression" in self.model_fields_set:
            _dict['expression'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BiobankSample from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "materialType": obj.get("materialType"),
            "sampleId": obj.get("sampleId"),
            "sampleIdUpper": obj.get("sampleIdUpper"),
            "sex": obj.get("sex"),
            "rin": obj.get("rin"),
            "hasGTExImage": obj.get("hasGTExImage"),
            "concentration": obj.get("concentration"),
            "autolysisScore": obj.get("autolysisScore"),
            "analysisRelease": obj.get("analysisRelease"),
            "genotype": obj.get("genotype"),
            "hardyScale": obj.get("hardyScale"),
            "pathologyNotes": obj.get("pathologyNotes"),
            "subjectId": obj.get("subjectId"),
            "tissueSiteDetailId": obj.get("tissueSiteDetailId"),
            "hasGenotype": obj.get("hasGenotype"),
            "originalMaterialType": obj.get("originalMaterialType"),
            "aliquotId": obj.get("aliquotId"),
            "tissueSampleId": obj.get("tissueSampleId"),
            "ageBracket": obj.get("ageBracket"),
            "brainTissueDonor": obj.get("brainTissueDonor"),
            "volume": obj.get("volume"),
            "hasExpressionData": obj.get("hasExpressionData"),
            "hasBRDImage": obj.get("hasBRDImage"),
            "tissueSiteDetail": obj.get("tissueSiteDetail"),
            "pathologyNotesCategories": obj.get("pathologyNotesCategories"),
            "amount": obj.get("amount"),
            "mass": obj.get("mass"),
            "tissueSite": obj.get("tissueSite"),
            "expression": obj.get("expression")
        })
        return _obj


