# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Chromosome(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    CHR1 = 'chr1'
    CHR10 = 'chr10'
    CHR11 = 'chr11'
    CHR12 = 'chr12'
    CHR13 = 'chr13'
    CHR14 = 'chr14'
    CHR15 = 'chr15'
    CHR16 = 'chr16'
    CHR17 = 'chr17'
    CHR18 = 'chr18'
    CHR19 = 'chr19'
    CHR2 = 'chr2'
    CHR20 = 'chr20'
    CHR21 = 'chr21'
    CHR22 = 'chr22'
    CHR3 = 'chr3'
    CHR4 = 'chr4'
    CHR5 = 'chr5'
    CHR6 = 'chr6'
    CHR7 = 'chr7'
    CHR8 = 'chr8'
    CHR9 = 'chr9'
    CHRM = 'chrM'
    CHRX = 'chrX'
    CHRY = 'chrY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Chromosome from a JSON string"""
        return cls(json.loads(json_str))


