# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from gtex_openapi.models.app_models_responses_genome_build import AppModelsResponsesGenomeBuild
from gtex_openapi.models.chromosome import Chromosome
from typing import Optional, Set
from typing_extensions import Self

class GWAS(BaseModel):
    """
    GWAS
    """ # noqa: E501
    chromosome: Chromosome
    start: StrictInt
    end: StrictInt
    phenotype: StrictStr
    p_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="pValue")
    beta: Optional[Union[StrictFloat, StrictInt]] = None
    pubmed_id: StrictInt = Field(alias="pubmedId")
    snp_id: StrictStr = Field(alias="snpId")
    risk_allele: Optional[StrictStr] = Field(default=None, alias="riskAllele")
    genome_build: AppModelsResponsesGenomeBuild = Field(alias="genomeBuild")
    __properties: ClassVar[List[str]] = ["chromosome", "start", "end", "phenotype", "pValue", "beta", "pubmedId", "snpId", "riskAllele", "genomeBuild"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GWAS from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if p_value (nullable) is None
        # and model_fields_set contains the field
        if self.p_value is None and "p_value" in self.model_fields_set:
            _dict['pValue'] = None

        # set to None if beta (nullable) is None
        # and model_fields_set contains the field
        if self.beta is None and "beta" in self.model_fields_set:
            _dict['beta'] = None

        # set to None if risk_allele (nullable) is None
        # and model_fields_set contains the field
        if self.risk_allele is None and "risk_allele" in self.model_fields_set:
            _dict['riskAllele'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GWAS from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chromosome": obj.get("chromosome"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "phenotype": obj.get("phenotype"),
            "pValue": obj.get("pValue"),
            "beta": obj.get("beta"),
            "pubmedId": obj.get("pubmedId"),
            "snpId": obj.get("snpId"),
            "riskAllele": obj.get("riskAllele"),
            "genomeBuild": obj.get("genomeBuild")
        })
        return _obj


