# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from gtex_openapi.models.single_tissue_eqtl import SingleTissueEqtl
from typing import Optional, Set
from typing_extensions import Self

class IGVResponse(BaseModel):
    """
    IGVResponse
    """ # noqa: E501
    dataset_id: StrictStr = Field(alias="datasetId")
    single_tissue_eqtl: List[SingleTissueEqtl] = Field(alias="singleTissueEqtl")
    __properties: ClassVar[List[str]] = ["datasetId", "singleTissueEqtl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IGVResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in single_tissue_eqtl (list)
        _items = []
        if self.single_tissue_eqtl:
            for _item_single_tissue_eqtl in self.single_tissue_eqtl:
                if _item_single_tissue_eqtl:
                    _items.append(_item_single_tissue_eqtl.to_dict())
            _dict['singleTissueEqtl'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IGVResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datasetId": obj.get("datasetId"),
            "singleTissueEqtl": [SingleTissueEqtl.from_dict(_item) for _item in obj["singleTissueEqtl"]] if obj.get("singleTissueEqtl") is not None else None
        })
        return _obj


