# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PathCategory(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    ADENOMA = 'adenoma'
    AMYLACEA = 'amylacea'
    ATELECTASIS = 'atelectasis'
    ATHEROSCLEROSIS = 'atherosclerosis'
    ATHEROSIS = 'atherosis'
    ATROPHY = 'atrophy'
    CALCIFICATION = 'calcification'
    CIRRHOSIS = 'cirrhosis'
    CLEAN_SPECIMENS = 'clean_specimens'
    CONGESTION = 'congestion'
    CORPORA_ALBICANTIA = 'corpora_albicantia'
    CYST = 'cyst'
    DESQUAMATION = 'desquamation'
    DIABETIC = 'diabetic'
    DYSPLASIA = 'dysplasia'
    EDEMA = 'edema'
    EMPHYSEMA = 'emphysema'
    ESOPHAGITIS = 'esophagitis'
    FIBROSIS = 'fibrosis'
    GASTRITIS = 'gastritis'
    GLOMERULOSCLEROSIS = 'glomerulosclerosis'
    GOITER = 'goiter'
    GYNECOMASTOID = 'gynecomastoid'
    HASHIMOTO = 'hashimoto'
    HEART_FAILURE_CELLS = 'heart_failure_cells'
    HEMORRHAGE = 'hemorrhage'
    HEPATITIS = 'hepatitis'
    HYALINIZATION = 'hyalinization'
    HYPEREOSINOPHILIA = 'hypereosinophilia'
    HYPERPLASIA = 'hyperplasia'
    HYPERTROPHY = 'hypertrophy'
    HYPOXIC = 'hypoxic'
    INFARCTION = 'infarction'
    INFLAMMATION = 'inflammation'
    ISCHEMIC_CHANGES = 'ischemic_changes'
    MACROPHAGES = 'macrophages'
    MASTOPATHY = 'mastopathy'
    METAPLASIA = 'metaplasia'
    MONCKEBERG = 'monckeberg'
    NECROSIS = 'necrosis'
    NEPHRITIS = 'nephritis'
    NEPHROSCLEROSIS = 'nephrosclerosis'
    NO_ABNORMALITIES = 'no_abnormalities'
    NODULARITY = 'nodularity'
    PANCREATITIS = 'pancreatitis'
    PIGMENT = 'pigment'
    PNEUMONIA = 'pneumonia'
    POST_MENOPAUSAL = 'post_menopausal'
    PROSTATITIS = 'prostatitis'
    SAPONIFICATION = 'saponification'
    SCARRING = 'scarring'
    SCLEROTIC = 'sclerotic'
    SOLAR_ELASTOSIS = 'solar_elastosis'
    SPERMATOGENESIS = 'spermatogenesis'
    STEATOSIS = 'steatosis'
    SWEAT_GLANDS = 'sweat_glands'
    TMA = 'tma'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PathCategory from a JSON string"""
        return cls(json.loads(json_str))


