# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from gtex_openapi.models.cell_type import CellType
from gtex_openapi.models.chromosome import Chromosome
from gtex_openapi.models.dataset_id import DatasetId
from gtex_openapi.models.tissue_site_detail_id import TissueSiteDetailId
from gtex_openapi.models.tissue_site_ontology_id import TissueSiteOntologyId
from typing import Optional, Set
from typing_extensions import Self

class SingleTissueISqtl(BaseModel):
    """
    SingleTissueISqtl
    """ # noqa: E501
    snp_id: Optional[StrictStr] = Field(default=None, alias="snpId")
    b_gise: Union[StrictFloat, StrictInt] = Field(alias="bGISE")
    pos: StrictInt
    snp_id_upper: Optional[StrictStr] = Field(default=None, alias="snpIdUpper")
    p_value_g: Union[StrictFloat, StrictInt] = Field(alias="pValueG")
    p_value_gi: Union[StrictFloat, StrictInt] = Field(alias="pValueGI")
    gene_symbol: StrictStr = Field(alias="geneSymbol")
    gene_symbol_upper: StrictStr = Field(alias="geneSymbolUpper")
    p_value_i: Union[StrictFloat, StrictInt] = Field(alias="pValueI")
    b_gi: Union[StrictFloat, StrictInt] = Field(alias="bGI")
    tissue_site_detail_id: TissueSiteDetailId = Field(alias="tissueSiteDetailId")
    ontology_id: TissueSiteOntologyId = Field(alias="ontologyId")
    chromosome: Chromosome
    tissue_cell_type: CellType = Field(alias="tissueCellType")
    tss_distance: StrictInt = Field(alias="tssDistance")
    b_gse: Union[StrictFloat, StrictInt] = Field(alias="bGSE")
    variant_id: StrictStr = Field(alias="variantId")
    maf: Union[StrictFloat, StrictInt]
    b_ise: Union[StrictFloat, StrictInt] = Field(alias="bISE")
    dataset_id: DatasetId = Field(alias="datasetId")
    b_g: Union[StrictFloat, StrictInt] = Field(alias="bG")
    p_value_adjusted_bh: Union[StrictFloat, StrictInt] = Field(alias="pValueAdjustedBH")
    b_i: Union[StrictFloat, StrictInt] = Field(alias="bI")
    gencode_id: StrictStr = Field(alias="gencodeId")
    phenotype_id: StrictStr = Field(alias="phenotypeId")
    __properties: ClassVar[List[str]] = ["snpId", "bGISE", "pos", "snpIdUpper", "pValueG", "pValueGI", "geneSymbol", "geneSymbolUpper", "pValueI", "bGI", "tissueSiteDetailId", "ontologyId", "chromosome", "tissueCellType", "tssDistance", "bGSE", "variantId", "maf", "bISE", "datasetId", "bG", "pValueAdjustedBH", "bI", "gencodeId", "phenotypeId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SingleTissueISqtl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if snp_id (nullable) is None
        # and model_fields_set contains the field
        if self.snp_id is None and "snp_id" in self.model_fields_set:
            _dict['snpId'] = None

        # set to None if snp_id_upper (nullable) is None
        # and model_fields_set contains the field
        if self.snp_id_upper is None and "snp_id_upper" in self.model_fields_set:
            _dict['snpIdUpper'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SingleTissueISqtl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "snpId": obj.get("snpId"),
            "bGISE": obj.get("bGISE"),
            "pos": obj.get("pos"),
            "snpIdUpper": obj.get("snpIdUpper"),
            "pValueG": obj.get("pValueG"),
            "pValueGI": obj.get("pValueGI"),
            "geneSymbol": obj.get("geneSymbol"),
            "geneSymbolUpper": obj.get("geneSymbolUpper"),
            "pValueI": obj.get("pValueI"),
            "bGI": obj.get("bGI"),
            "tissueSiteDetailId": obj.get("tissueSiteDetailId"),
            "ontologyId": obj.get("ontologyId"),
            "chromosome": obj.get("chromosome"),
            "tissueCellType": obj.get("tissueCellType"),
            "tssDistance": obj.get("tssDistance"),
            "bGSE": obj.get("bGSE"),
            "variantId": obj.get("variantId"),
            "maf": obj.get("maf"),
            "bISE": obj.get("bISE"),
            "datasetId": obj.get("datasetId"),
            "bG": obj.get("bG"),
            "pValueAdjustedBH": obj.get("pValueAdjustedBH"),
            "bI": obj.get("bI"),
            "gencodeId": obj.get("gencodeId"),
            "phenotypeId": obj.get("phenotypeId")
        })
        return _obj


