# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SortBy(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    SAMPLEID = 'sampleId'
    TISSUESAMPLEID = 'tissueSampleId'
    SUBJECTID = 'subjectId'
    MATERIALTYPE = 'materialType'
    ORIGINALMATERIALTYPE = 'originalMaterialType'
    TISSUESITEDETAILID = 'tissueSiteDetailId'
    SEX = 'sex'
    AGEBRACKET = 'ageBracket'
    HARDYSCALE = 'hardyScale'
    HASEXPRESSIONDATA = 'hasExpressionData'
    HASGENOTYPE = 'hasGenotype'
    BRAINTISSUEDONOR = 'brainTissueDonor'
    AUTOLYSISSCORE = 'autolysisScore'
    RIN = 'rin'
    AMOUNT = 'amount'
    VOLUME = 'volume'
    CONCENTRATION = 'concentration'
    MASS = 'mass'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SortBy from a JSON string"""
        return cls(json.loads(json_str))


