# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gtex_openapi.models.app_models_responses_hardy_scale import AppModelsResponsesHardyScale
from gtex_openapi.models.donor_age_bracket import DonorAgeBracket
from gtex_openapi.models.sex import Sex
from typing import Optional, Set
from typing_extensions import Self

class Subject(BaseModel):
    """
    Subject
    """ # noqa: E501
    hardy_scale: Optional[AppModelsResponsesHardyScale] = Field(default=None, alias="hardyScale")
    age_bracket: DonorAgeBracket = Field(alias="ageBracket")
    subject_id: StrictStr = Field(alias="subjectId")
    sex: Sex
    dataset_id: StrictStr = Field(alias="datasetId")
    __properties: ClassVar[List[str]] = ["hardyScale", "ageBracket", "subjectId", "sex", "datasetId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hardyScale": obj.get("hardyScale"),
            "ageBracket": obj.get("ageBracket"),
            "subjectId": obj.get("subjectId"),
            "sex": obj.get("sex"),
            "datasetId": obj.get("datasetId")
        })
        return _obj


