# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TissueSiteDetailId(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    ADIPOSE_SUBCUTANEOUS = 'Adipose_Subcutaneous'
    ADIPOSE_VISCERAL_OMENTUM = 'Adipose_Visceral_Omentum'
    ADRENAL_GLAND = 'Adrenal_Gland'
    ARTERY_AORTA = 'Artery_Aorta'
    ARTERY_CORONARY = 'Artery_Coronary'
    ARTERY_TIBIAL = 'Artery_Tibial'
    BLADDER = 'Bladder'
    BRAIN_AMYGDALA = 'Brain_Amygdala'
    BRAIN_ANTERIOR_CINGULATE_CORTEX_BA24 = 'Brain_Anterior_cingulate_cortex_BA24'
    BRAIN_CAUDATE_BASAL_GANGLIA = 'Brain_Caudate_basal_ganglia'
    BRAIN_CEREBELLAR_HEMISPHERE = 'Brain_Cerebellar_Hemisphere'
    BRAIN_CEREBELLUM = 'Brain_Cerebellum'
    BRAIN_CORTEX = 'Brain_Cortex'
    BRAIN_FRONTAL_CORTEX_BA9 = 'Brain_Frontal_Cortex_BA9'
    BRAIN_HIPPOCAMPUS = 'Brain_Hippocampus'
    BRAIN_HYPOTHALAMUS = 'Brain_Hypothalamus'
    BRAIN_NUCLEUS_ACCUMBENS_BASAL_GANGLIA = 'Brain_Nucleus_accumbens_basal_ganglia'
    BRAIN_PUTAMEN_BASAL_GANGLIA = 'Brain_Putamen_basal_ganglia'
    BRAIN_SPINAL_CORD_CERVICAL_C_MINUS_1 = 'Brain_Spinal_cord_cervical_c-1'
    BRAIN_SUBSTANTIA_NIGRA = 'Brain_Substantia_nigra'
    BREAST_MAMMARY_TISSUE = 'Breast_Mammary_Tissue'
    CELLS_CULTURED_FIBROBLASTS = 'Cells_Cultured_fibroblasts'
    CELLS_EBV_MINUS_TRANSFORMED_LYMPHOCYTES = 'Cells_EBV-transformed_lymphocytes'
    CELLS_TRANSFORMED_FIBROBLASTS = 'Cells_Transformed_fibroblasts'
    CERVIX_ECTOCERVIX = 'Cervix_Ectocervix'
    CERVIX_ENDOCERVIX = 'Cervix_Endocervix'
    COLON_SIGMOID = 'Colon_Sigmoid'
    COLON_TRANSVERSE = 'Colon_Transverse'
    ESOPHAGUS_GASTROESOPHAGEAL_JUNCTION = 'Esophagus_Gastroesophageal_Junction'
    ESOPHAGUS_MUCOSA = 'Esophagus_Mucosa'
    ESOPHAGUS_MUSCULARIS = 'Esophagus_Muscularis'
    FALLOPIAN_TUBE = 'Fallopian_Tube'
    HEART_ATRIAL_APPENDAGE = 'Heart_Atrial_Appendage'
    HEART_LEFT_VENTRICLE = 'Heart_Left_Ventricle'
    KIDNEY_CORTEX = 'Kidney_Cortex'
    KIDNEY_MEDULLA = 'Kidney_Medulla'
    LIVER = 'Liver'
    LUNG = 'Lung'
    MINOR_SALIVARY_GLAND = 'Minor_Salivary_Gland'
    MUSCLE_SKELETAL = 'Muscle_Skeletal'
    NERVE_TIBIAL = 'Nerve_Tibial'
    OVARY = 'Ovary'
    PANCREAS = 'Pancreas'
    PITUITARY = 'Pituitary'
    PROSTATE = 'Prostate'
    SKIN_NOT_SUN_EXPOSED_SUPRAPUBIC = 'Skin_Not_Sun_Exposed_Suprapubic'
    SKIN_SUN_EXPOSED_LOWER_LEG = 'Skin_Sun_Exposed_Lower_leg'
    SMALL_INTESTINE_TERMINAL_ILEUM = 'Small_Intestine_Terminal_Ileum'
    SPLEEN = 'Spleen'
    STOMACH = 'Stomach'
    TESTIS = 'Testis'
    THYROID = 'Thyroid'
    UTERUS = 'Uterus'
    VAGINA = 'Vagina'
    WHOLE_BLOOD = 'Whole_Blood'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TissueSiteDetailId from a JSON string"""
        return cls(json.loads(json_str))


