# coding: utf-8

"""
    GTEx Portal API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Units(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    TPM = 'TPM'
    READ_COUNT = 'read count'
    LOG_LEFT_PARENTHESIS_CP10_K_RIGHT_PARENTHESIS = 'log(CP10K)'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Units from a JSON string"""
        return cls(json.loads(json_str))


